services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the entire project directory
    environment:
      - PYTHONUNBUFFERED=1
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - ENVIRONMENT=development
      - PYTHONPATH=/app
    depends_on:
      loki:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  loki:
    image: grafana/loki:2.9.2
    user: "0:0"  # Run as root to avoid permission issues
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki_data:/loki
      - ./loki_tmp:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      loki:
        condition: service_healthy
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_LOG_LEVEL=debug
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3 